services:
  app:
    build: .
    container_name: escola_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/escola?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: escola_user
      SPRING_DATASOURCE_PASSWORD: escola_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - escola_net

  db:
    image: mysql:8.1
    container_name: escola_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: escola
      MYSQL_USER: escola_user
      MYSQL_PASSWORD: escola_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - escola_net

volumes:
  db_data:

networks:
  escola_net:
