spring:
  datasource:
    url: jdbc:mysql://db:3306/escola?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: escola_user
    password: escola_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  sql:
    init:
      mode: always

  security:
    user:
      name: Mark
      password: 233234
      roles: ADMIN
