spring:
  datasource:
    url: jdbc:mysql://localhost:3306/escola_db?useSSL=false&serverTimezone=UTC
    username: escola_user
    password: senha_forte_aqui

  jpa:
    hibernate:
      ddl-auto: create-drop   # recria tabelas toda vez
    properties:
      hibernate:
        sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  security:
    user:
      name: Mark
      password: 233234
      roles: ADMIN
